### ISSUE TITLE
to-jsonlz4 compressor

### ISSUE THREAD

**Issue by Allasso** [avih/dejsonlz4#4] opened 2017-09-10 11:43 UTC
Thanks for app, Avi, compiled and worked nicely on OS X.

Any chance of you creating a to-jsonlz4 compressor?

**Comment by avih** [comment] 2017-09-10 13:09
It's at `src/ref_compress` .

Duplicate of #2 .

**Closed as completed by avih** 2017-09-10 13:09 UTC

**Comment by Allasso** [comment] 2017-09-10 13:39
Thanks.

According to readme in that directory:

"jsonlz4 - Reference compressor to the same non standard lz4-based format which Firefox uses for its bookmark backups.

This tool is here for reference only, and it's not fully tested. **It's not recommended to use** it since we don't want to create files in a non standard format, even if Firefox does so too."

But I'll give it a try.
